services:
  - type: web
    name: aird-dashboard
    env: python
    plan: free
    autoDeploy: true

    buildCommand: pip install -r requirements.txt
    startCommand: python src/app.py

    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      # Set in Render dashboard (don’t commit secrets)
      - key: SLACK_WEBHOOK_URL
        sync: false

    healthCheckPath: /